
---
# Task for installing and configuring mysql

- name: Install python dependencies
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - 'python'
    - 'python-setuptools'
    - 'python-devel'
    - '@Development tools'
    - 'python2-pip'
    - 'python36-pip'

- name: Install mysql rpm repository
  become: yes
  yum:
    name: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
    state: present

- name: Install mysql and mysql-server
  become: yes
  yum:
    name: "{{ item }}"
  loop:
    - 'mysql'
    - 'mysql-server'
    - 'MySQL-python'

- name: Start mysql service
  become: yes
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create database
  become: yes
  mysql_db:
    name: "{{ db_name }}"
    state: present

- name: Create a user
  become: yes
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "*.*:ALL"
    host: "%"
    state: present
    
  






...
  
