
---

- name: Install python dependencies
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - 'python'
    - 'python-setuptools'
    - 'python-devel'
    - '@Development tools'
    - 'python-pip'

- name: Install mysql rpm repository
  become: yes
  yum:
    name: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
    state: present

- name: Install mysql and mysql-server
  become: yes
  yum:
    name: "{{ item }}"
  loop:
    - mysql
    - mysql-server
    
  






...
  
